term_palette: 191724;eb6f92;9ccfd8;f6c177;31748f;c4a7e7;9ccfd8;e0def4
term_palette_bright: 6e6a86;eb6f92;9ccfd8;f6c177;31748f;c4a7e7;9ccfd8;e0def4
term_foreground: e0def4
term_foreground_bright: e0def4

wallpaper: boot():/limine/wallpaper.jpg#9b0d8bc381ddfee7ea03c474aa98204c47aba837331faa1571ee66f7211ef846e470819e53efb399f5a9c567448544554ada0f45746675a5a7f9e910ca3d4ae8
wallpaper_style: stretched

timeout: 3

/Arch Linux (linux)
    protocol: efi
    path: boot():/EFI/Linux/arch-linux.efi
    cmdline: root=/dev/ArchinstallVg/root zswap.enabled=0 rootflags=subvol=@ rw rootfstype=btrfs
